import { NavigatorContext } from "@coveo/headless-react/ssr-commerce";
import { cookies, headers as nextHeaders } from "next/headers";

/**
 * This class implements the NavigatorContext interface from Coveo's SSR commerce sub-package.
 * It is designed to work within a Next.js environment, providing a way to extract
 * navigation-related context from Next.js request headers. This context will then be
 * pass to subsequent search requests.
 */
export class NextJsNavigatorContext implements NavigatorContext {
  /**
   * Initializes a new instance of the NextJsNavigatorContext class.
   * @param headers The readonly headers from a Next.js request, providing access to request-specific data.
   */
  constructor(private headers: ReturnType<typeof nextHeaders>) {}

  /**
   * Retrieves the referrer URL from the request headers.
   * Some browsers use 'referer' while others may use 'referrer'.
   * @returns The referrer URL if available, otherwise undefined.
   */
  get referrer() {
    return this.headers.get("referer") || this.headers.get("referrer");
  }

  /**
   * Retrieves the user agent string from the request headers.
   * @returns The user agent string if available, otherwise undefined.
   */
  get userAgent() {
    return this.headers.get("user-agent");
  }

  /**
   * Retrieves the current page URL from the 'x-href' header, which can represent
   * the application's active location or requested resource URL.
   * This header may be set by middleware or server logic to reflect the active location.
   * @returns The current location URL if available, otherwise undefined.
   */
  get location() {
    return this.headers.get("x-href");
  }

  /**
   * Fetches the unique visitor ID from the coveo_visitorId cookie that was generated by the middleware.
   * @returns The visitor ID as the client ID.
   * @throws Error if the visitor ID cookie is not found.
   */
  get clientId() {
    const cookieStore = cookies();
    const visitorId = cookieStore.get("coveo_visitorId")?.value;

    if (!visitorId) {
      throw new Error("Visitor ID cookie (coveo_visitorId) not found. Ensure middleware is properly configured.");
    }

    return visitorId;
  }

  /**
   * Marshals the navigation context into a format that can be used by Coveo's headless library.
   * @returns An object containing clientId, location, referrer, and userAgent properties.
   */
  get marshal(): NavigatorContext {
    return {
      clientId: this.clientId,
      location: this.location,
      referrer: this.referrer,
      userAgent: this.userAgent,
    };
  }
}
